[package]
name = "gemm_tiled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cust = "0.3"
nanorand = "0.6.1"

[build-dependencies]
cuda_builder = "0.3"
